language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
install:
- npm install
before_script:
# Necessary to run test on Travis CI that require a graphical interface.
# See https://docs.travis-ci.com/user/gui-and-headless-browsers
- gulp prod
script:
- gulp karma
